### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#120]
Have you considered adding a common prefix such as `Mdc` to all component class names? This would help avoid naming conflicts, and would probably become harder to do the longer time goes on.

**Comment by trimox** [comment]
@rapropos I agree, and very true regarding tech debt on this issue. Since we're talking about a significant breaking change, it'll benefit everyone if we get this over with now.

- [ ] Prefix component/directive classes with `Mdc` (e.g. `MdcButtonComponent`, `MdcElevationDirective`)
- [ ] Prefix exported class name of component modules (e.g. `MdcButtonModule`)  
- [ ] Update documentation
- [ ] Include "breaking change" message w/explanation
