### ISSUE TITLE
Fix runtime errors in non-browser environments

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#1268]
First of all, a huge thank you to @JeetChaudhari for his work on resolving server side rendering issues #1240. He alerted me that some components are experiencing runtime issues outside of these fixes.

#### Research
My investigation found TypeScript preserves the type information of methods with decorators, and when one of the arguments for the method is a native Event type, this preserved type information can lead to runtime errors in non-browser environments.

#### Recommendation
We use directive configuration instead of `@HostBinding` and `@HostListener`.

**Comment by trimox** [comment]
Lot's of progress on this issue. Anyone available for testing server side rendering?

**Comment by JeetChaudhari** [comment]
@trimox I will test it tonight. Thank You

**Comment by trimox** [comment]
@JeetChaudhari Thanks! Pushing a minor bug-fix release v0.39.1 today, but nothing related to server rendering.

**Comment by trimox** [comment]
@JeetChaudhari Any luck man?

**Comment by JeetChaudhari** [comment]
My Laptop's power supply broken bro, have ordered online but didn't received yet so could not test.Sorry bro.On 15-Sep-2018 7:44 PM, Dominic Carretto <notifications@github.com> wrote:@JeetChaudhari Any luck man?

**Comment by trimox** [comment]
@JeetChaudhari Ouch! That's a bummer. No worries..Hope you get back up and running soon!

**Comment by JeetChaudhari** [comment]
@trimox Sorry for the delay. I got my power supply but it seems duplicate. Anyways as it gets work done, I tried to test server-side build for demos folder in this repo. However, even without using server side, normally my build failed with an error.

ERROR in node_modules/@angular-mdc/web/textfield/typings/helper-text.d.ts(2,50): error TS2307: Cannot find module '@material/textfield/helper-text'.
node_modules/@angular-mdc/web/textfield/typings/text-field-icon.d.ts(3,44): error TS2307: Cannot find module '@material/textfield/icon'.

Can you please get it fixed so that I can test this further?

**Comment by trimox** [comment]
Closing with #1381 

If we find other issues, we'll fix.
