### ISSUE TITLE
Snackbar does not go away if you change browser tab

### ISSUE THREAD

**Issue by zunamo** [trimox/angular-mdc-web#1548]
### What Angular MDC version are you using?
0.41.1

### What browser(s) is this bug affecting?
Chrome, Edge, Firefox

### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?
Show snackbar, switch browser tab or click a link that opens another browser tab.
https://trimox.github.io/angular-mdc-web/#/snackbar-demo

### What is the expected behavior?
Snackbar should always go away

### What is the actual behavior?
Snackbar stays in the screen. It only goes away after the action is clicked, but you can also have snackbars without action.

**Comment by trimox** [comment]
@zunamo Thanks for reporting this.

I checked upstream [material-components](https://github.com/material-components/material-components-web) and found a long standing open issue; https://github.com/material-components/material-components-web/issues/1398

@Garbee made a good point for screen readers. 
> I'd assume this is when the tab is switched back to the MCW tab being active. The snackbar is given focus since it is used as a priority message system that users may need to interact with within the given time constraint. So making that the focus before returning to page focus is there for screen readers and other accessible technology. This way, users actually get the information provided.

Also, the MDC team is currently reimplementing Snackbar to more closely match the latest Material spec. We'll see if this is included..
reference: https://github.com/material-components/material-components-web/pull/4091

**Comment by trimox** [comment]
Going to add an override for closing snackbar based on timeout value.

**Comment by Garbee** [comment]
The problem with providing an override here is in this situation:

1. User triggers action on page
2. User switches tabs while that processes
3. Comes back after timeout completes, so message is gone.

How does the user then know if the action succeeded/failed/etc? Developers are notoriously lazy when it comes to user experiences. If you override the visibility requirement then there are many situations where a user may never get feedback about the success of an action.

> Snackbar stays in the screen. It only goes away after the action is clicked, but you can also have snackbars without action.

It sounds to me like if you change tabs, the visibility API isn't being used to re-trigger the timeout queue for the messages. Which is a bug either in the angular implementation here or upstream, I'm not sure which since I haven't looked at the code. That is a core root issue that needs to be addressed. Rather than providing a method that can hinder user experiences.

**Comment by trimox** [comment]
@Garbee Appreciate your input, and as usual great points. I was secretly hoping to lure you with the mention earlier :smile:, always found your insight on [material-components-web](https://github.com/material-components/material-components-web) helpful. 

In my haste writing my comment earlier, I meant to add _optional_ override; requiring developers to pass a flag via `MdcSnackbarConfig` to remove a snackbar after timeout. Default behavior following MDC / Material specs still.

Since `MDCSnackbar` is in the process of re-implementation upstream; think it best we wait and see if it's addressed inside the MDC Snackbar Foundation. If not, we can definitely revisit as enhancement..

**Comment by Garbee** [comment]
When doing the initial docs around what became MCW we opted to do our best to never provide options that gave an inferior user experience. Instead forcing a better UX (as defined by the spec, which as far as we could tell in this case what we did held true to the spec) since that is what users deserve.

If people want to give bad experiences to users, they should work for it.

**Comment by zunamo** [comment]
What about checking for tab change (window focus) to deal with this problem? If this is possible, it would work around the UX issue.

**Comment by Garbee** [comment]
The same (Window Visibility) API that is used to detect a tab switch to pause the queue is the same one that should be used to restart the queue timing when the tab is switched back to. As I said previously, if it isn't doing that by default then it is a bug in the implementation.

Switching tabs should not cause an infinitely appearing snackbar. Those don't exist in the specification.

**Comment by acdvorak** [comment]
The upcoming snackbar rewrite (see https://github.com/material-components/material-components-web/pull/4091) should not have this problem, because we're removing the `visibilitychange` and `focus`/`blur` handlers
(to avoid bugs like this one).

**Comment by trimox** [comment]
PR ready, preparing v0.43.0 release. Tested, and looks great.
