### ISSUE TITLE
Active mdc-tab

### ISSUE THREAD

**Issue by Eski** [trimox/angular-mdc-web#349]
Hi, 

I'm actually working with tabs and notice that you can't set active to mdc-tab based on route url.
Here a example : 
```
<mdc-tab routerLink="/sales/create" [active]="router.isActive('/sales/create')">
      Saisie vente
</mdc-tab>
```

With this approach, the mdc-tab get the **.mdc-tab--active** class but the tab line stay in the initial position.

<img src="https://img4.hostingpics.net/pics/616186tablinebug.jpg">

**Comment by trimox** [comment]
Good catch. I finished implementing MDC Dialog service today, and can resolve some of these smaller issues now.

**Comment by trimox** [comment]
PR incoming today.

**Comment by trimox** [comment]
Hey @Eski Could you review my examples below and see if they work for you? I'll hold off on code change until I hear back.

```html
<mdc-tab routerLink="/sales/create" routerLinkActive #rla="routerLinkActive" 
  [active]="rla.isActive">
  Saisie vente
</mdc-tab>
```
Also, here's an example with an *ngFor
```html
<mdc-tab-bar>
  <mdc-tab *ngFor="let tabLink of tabLinks" [routerLink]="[{outlets: {taboutlet: tabLink.link}}]"
    routerLinkActive #rla="routerLinkActive" [active]="rla.isActive">{{tabLink.label}}</mdc-tab>
</mdc-tab-bar>
```

**Comment by Eski** [comment]
It's the same thing as before.
My example below works if you have route with children.

**Comment by trimox** [comment]
Kk. I'm testing some changes to that would handle tab routing with url's.

**Comment by trimox** [comment]
@Eski I got this working in PR #369 👍 

Finishing up a couple PR minor to-do items, and I'll merge.

**Comment by phutaneVinayak** [comment]
> Hey @ESKI Could you review my examples below and see if they work for you? I'll hold off on code change until I hear back.
> 
> ```
> <mdc-tab routerLink="/sales/create" routerLinkActive #rla="routerLinkActive" 
>   [active]="rla.isActive">
>   Saisie vente
> </mdc-tab>
> ```
> 
> Also, here's an example with an *ngFor
> 
> ```
> <mdc-tab-bar>
>   <mdc-tab *ngFor="let tabLink of tabLinks" [routerLink]="[{outlets: {taboutlet: tabLink.link}}]"
>     routerLinkActive #rla="routerLinkActive" [active]="rla.isActive">{{tabLink.label}}</mdc-tab>
> </mdc-tab-bar>
> ```

hi,
i implemented above code, but i am getting Can't bind to 'active' since it isn't a known property of 'mdc-tab'.

i am on  Angular 7

Error stack :- 

core.js:15714 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'active' since it isn't a known property of 'mdc-tab'.
1. If 'mdc-tab' is an Angular component and it has 'active' input, then verify that it is part of this module.
2. If 'mdc-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          routerLinkActive 
          #rla="routerLinkActive"
          [ERROR ->][(active)]="rla.isActive"
           >
            
"): ng:///TripsModule/TripDetailComponent.html@12:10
Error: Template parse errors:
Can't bind to 'active' since it isn't a known property of 'mdc-tab'.
1. If 'mdc-tab' is an Angular component and it has 'active' input, then verify that it is part of this module.
2. If 'mdc-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          routerLinkActive 
          #rla="routerLinkActive"
          [ERROR ->][(active)]="rla.isActive"
           >
            
"): ng:///TripsModule/TripDetailComponent.html@12:10
    at syntaxError (compiler.js:2426)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:20600)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:26146)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:26133)
    at compiler.js:26076
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:26076)
    at compiler.js:25986
    at Object.then (compiler.js:2417)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:25985)
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17280)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
defaultErrorLogger @ core.js:15714
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15762
next @ core.js:17761
schedulerFn @ core.js:13504
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:13488
(anonymous) @ core.js:17311
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17248
onHandleError @ core.js:17311
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
push../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ zone.js:164
_loop_1 @ zone.js:694
api.microtaskDrainDone @ zone.js:703
drainMicroTaskQueue @ zone.js:608
Promise.then (async)
scheduleMicroTask @ zone.js:584
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
onScheduleTask @ zone.js:301
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:258
scheduleResolveOrReject @ zone.js:879
resolvePromise @ zone.js:825
(anonymous) @ zone.js:741
webpackJsonpCallback @ bootstrap:25
(anonymous) @ trips-trips-module.js:1

**Comment by makinori** [comment]
`mdc-tab` `active` property is gone. Is there any other way to do this easily?

**Comment by hyst3ric41** [comment]
> `mdc-tab` `active` property is gone. Is there any other way to do this easily?

Hello @makitsune 

I used the `mdc-tab` `disabled` property to do the trick through a simple function:

```
<mdc-tab-bar #mdc_tab_bar_id>
   <mdc-tab-scroller>
      <mdc-tab
        *ngFor="let tab of myTabs; index as i"
        [routerLink]="[tab.link]"
        routerLinkActive
        #routerActiveFixer="routerLinkActive"
        [disabled]="canalizeActiveTab(routerActiveFixer.isActive, i)"
        >
         <mdc-tab-label>{{tab.label}}</mdc-tab-label>
      </mdc-tab>
   </mdc-tab-scroller>
</mdc-tab-bar>
```
Capture the `tab-bar element` through @ViewChild and then:
```
canalizeActiveTab(isActive:boolean, tabIndex:number) {
   if (isActive) {
      this.tabsElement.activateTab(tabIndex);
   }
   return false;
}
```
It's a little tricky way but it works, I hope @trimox can restore the property soon.
