### ISSUE TITLE
Investigate Angular-CLI issues

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#87]
Looking into reported problem generating project with angular-cli.

**Comment by joradom** [comment]
hello trimox, I got it to work with angular-cli. My problem was I tried to import material-web-components-web.scss and I got an error from the scss processor ...  which is k

the fix is to put the path  to node-modules in angular-cli.json for the styles preprocessor:
 "stylePreprocessorOptions": {
        "includePaths": [
          "../node_modules"
        ]
      },
https://github.com/angular/angular-cli/wiki/angular-cli

at the moment I got a simple app with the toolbar and the drawer working and getting the basic css styles from the cdn. I keep going on making a simple demo site ...

btw: I'm very interested in this project, but I'm pretty newbie in angular and javascript. What kind of help can I bring to the project?

**Comment by trimox** [comment]
@joradom Good to hear you figured it out! Apologies for the delay in responding.

Also, thank you for the help offer. I'd probably start with filing issues for bugs, or feature requests you'd like to see (e.g. angular-cli guide), subsequently please feel free to send a pull request to resolve 😄. 

I'm available for help at any point. Thanks again!

**Comment by trimox** [comment]
Closing.
