### ISSUE TITLE
MDC, Angular MDC, Angular Material choice

### ISSUE THREAD

**Issue by jim20100** [trimox/angular-mdc-web#904]
Hi,

I am quite newbie to Angular and Material.
Time is now to choose an approach to integrate Material Design in my Angular 2 project.

As I am not experimented in Angular yet, I don't understand what will be the big advantages to choose a wrapper solution like Angular Material or Angular MDC over using the MDC core project directly.

Maybe you can help me to understand why it is better or absolutely necessary to use this angular mdc wrapper?

If I understand, the wrapper is implemented independently from the core MDC library.
Is it just a wrapper around the core libraries, or a specific implementation?

Are there some features of the core MDC that are not available via the wrapper?
How the future developments in the core MDC have to be implemented in the wrapper?

There is one main contributor, does it mean that the project relies only on one developer?

Jim

**Comment by trimox** [comment]
@jim20100 Great choice incorporating Material Design into your next project!

> Maybe you can help me to understand why it is better or absolutely necessary to use this angular mdc wrapper?

Obviously I'm a bit biased here, but I'll offer my thoughts.
First and foremost, you can focus on project development activities instead of making idiomatic Angular  components. Another option to consider is, Angular MDC is licensed under the MIT License, meaning your welcome to clone and/or fork the project to modify as you see fit.

For a fair comparison of MDC-Web vs Material 2, I'd suggest [Material Components for the Web vs Angular Material 2](https://stackoverflow.com/questions/41180498/material-components-for-the-web-vs-angular-material-2)

> Is it just a wrapper around the core libraries, or a specific implementation?

Angular MDC incorporates MDC-Web via an advanced approach using [Foundations and Adapters](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md#the-advanced-approach-using-foundations-and-adapters).

The MDC-Web components are split into packages, each come with a Foundation class and an Adapter interface. The Foundation contains the business logic that best represents Material Design, without referring to any HTML. The Adapter interfaces with methods that the Foundation needs to implement Material Design business logic. 

> Are there some features of the core MDC that are not available via the wrapper?

The goal of Angular MDC, is to be a canonical implementation of MDC-Web for Angular; a complete match for component specifications as they are made available by the MDC-Web team.

> How the future developments in the core MDC have to be implemented in the wrapper?

Not quite sure I follow, could you elaborate?

> There is one main contributor, does it mean that the project relies only on one developer?

I am just one, but our community is fairly small at the moment. Notwithstanding, we've had excellent [contributors](https://github.com/trimox/angular-mdc-web/graphs/contributors) solve a range of issues and all contributions are appreciated! 😄

**Comment by jim20100** [comment]
Thx for your first answer.
Maybe my questions were not clear enough. I try another way.

As I Understand there is a philosophy for material described here: 
https://material.io/guidelines/

There are some usable and REAL implementations:
- MDL managed by google (https://getmdl.io/)
- MDC Web managed by google (replaces MDL)

specific to Angular:
- Angular Material 2 managed by third-party developers
- Angular MDC managed by third party developers

When you say about MDC Web it is a "canonical implementation", for me it has non sense, because it is a real implementation we can use it for real projects: https://material.io/components/web/docs/getting-started/?

I did not go into the detail of the implementation of the MDC Web by google, but it relies on css and javascript.
So does your implementation is just an additional layer/wrapper above the google code or a totally independent implementation of the components with no relation with the MDC Web by Google.
Angular Material 2 is for example a totally independent implementation.

So when I say: How the future developments in the core MDC have to be implemented in the wrapper?
You may understand that I want to understand if it will be fast to get new features via your Angular MDC.

I would be pleased to be contributor, but I have to find additional 24h in a day. :-)

Jim

**Comment by trimox** [comment]
@jim20100

>So does your implementation is just an additional layer/wrapper above the google code or a totally independent implementation of the components with no relation with the MDC Web by Google.
Angular Material 2 is for example a totally independent implementation.

We add an Angular layer via the MDC-Web Foundations and Adapters, meaning we depend on MDC Web to execute Material Design.

>So when I say: How the future developments in the core MDC have to be implemented in the wrapper?

MDC-Web normally publishes a new version every two-weeks, and it normally takes 2-3 weeks to implement those changes and publish a compatible Angular MDC release.

**Comment by trimox** [comment]
Closing.
